---
- hosts: "{{ server_name }}"
  become: yes
  gather_facts: yes

  tasks:
    - name: Check for drift in httpd.conf
      gen_diff:
        source: "/etc/httpd/conf/httpd.conf"
        target: "{{ lookup('template', 'templates/httpd.conf.j2') }}"
        source_type: file
        target_type: string
      register: out

    - block:
        - name: Config diff 
          debug: msg="{{out.diff.delta}}"

        - name: POST Request
          uri:
            url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/em_event"
            method: POST
            user: "{{ ansible_servicenow_user }}"
            password: "{{ ansible_servicenow_password }}"
            body:
              source: "Ansible Tower"
              node: "{{ ansible_hostname }}"
              type: "Ansible Events"
              resource: "config driff"
              description: "This is the configuration drift delta:\n{{ out.diff.delta }}"
              severity: 3
            status_code: 201
            force_basic_auth: yes
            body_format: json
          register: api

        - debug: msg="{{api}}"
      when: out.changed
