---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Check for drift in httpd.conf
      gen_diff:
        source: "/etc/httpd/conf/httpd.conf"
        target: "{{ lookup('template', 'templates/httpd.conf.j2') }}"
        source_type: file
        target_type: string
      register: out

    - block:

        - name: Config diff 
          debug: msg="{{out.diff.delta}}"

        - name: Log an incident ticket with Service Now
          snow_record:
            username: "{{ snow_username }}"
            password: "{{ snow_password }}"
            instance: "{{ snow_instance }}"
            state: present
            data:
              short_description: "Config drift detected at {{ inventory_hostname }}"
              severity: 3
              priority: 2
              work_notes: "Here is the diff:\n {{out.diff.delta}}"  
          register: api

        - debug: msg="{{api}}"
      when: out.changed
