---
- name: Patching server
  hosts: "{{ server_name }}"
  become: yes

  #vars:
  #  service_now_num: 

  tasks:
    - name: Patch server
      block:
#        - ec2_metadata_facts:
#
#        - ec2_instance_facts:
#            region: "{{ ansible_ec2_placement_region }}"
#            instance_ids: "{{ ansible_ec2_instance_id }}"
#          delegate_to: 127.0.0.1
#          become: no
#          register: ec2_info
#
#        - name: Taking snapshot on /dev/sda1
#          ec2_snapshot:
#            region: "{{ ansible_ec2_placement_region }}"
#            instance_id: "{{ ansible_ec2_instance_id }}"
#            device_name: /dev/sda1
#            description: "snapshot of /dev/sda1 for {{ ansible_ec2_instance_id }}"
#          delegate_to: 127.0.0.1
#          become: no

        - name: Ensure yum-utils is available
          yum:
            update_cache: yes
            name: yum-utils
            state: present

        # For demo purposes: This is to ensure an older version
        # can be installed
        - name: Remove package
          yum:
            name: "{{ item }}"
            state: absent
          with_items:
            - httpd
            - httpd-tools
          when: pkg_name == 'httpd'

        - name: Install older package
          yum:
            name: httpd-2.4.6-67.el7
            state: present
          when: pkg_name == 'httpd'

        - name: Get the list of rpms before patching
          shell: rpm -qa | sort
          args:
            warn: false
          register: before_patch
          
        - name: Update package "{{ pkg_name }}" to latest 
          yum:
            name: "{{ pkg_name }}"
            state: latest
            update_cache: yes
          #check_mode: yes
          
        - name: Get the list of rpms after Patching
          shell: rpm -qa | sort
          args:
            warn: false
          register: after_patch
          
        - name: Check for delta packages
          gen_diff:
            source: "{{ after_patch.stdout }}"
            target: "{{ before_patch.stdout }}"
            source_type: string
            target_type: string
          register: delta

        - debug: msg="{{delta.diff.delta}}"

        - name: Check if reboot is necessary.
          command: needs-restarting -r
          register: reboot_check
          changed_when: false
          failed_when: reboot_check.rc > 1

        - name: Reboot the machine if necessary.
          include_role:
            name: reboot
          when:
            - reboot_check.rc == 1

        - name: POST Request
          uri:
            url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/u_ansible_message_log"
            method: POST
            user: "{{ ansible_servicenow_user }}"
            password: "{{ ansible_servicenow_password }}"
            body:
              u_status: "success"
              u_action: "update_status"
              u_job_id: "{{ tower_job_id }}"
              u_comment: "Package difference:\n{{ delta.diff.delta }}"
            status_code: 201
            force_basic_auth: yes
            body_format: json
      rescue:
        - name: POST Request
          uri:
            url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/u_ansible_message_log"
            method: POST
            user: "{{ ansible_servicenow_user }}"
            password: "{{ ansible_servicenow_password }}"
            body:
              u_status: "fail"
              u_action: "update_status"
              u_job_id: "{{ tower_job_id }}"
            status_code: 201
            force_basic_auth: yes
            body_format: json
